FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
 
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["PioneerControlToMqtt.csproj", "./"]
RUN dotnet restore "./PioneerControlToMqtt.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "PioneerControlToMqtt.csproj" -c Release -o /app/build
 
FROM build AS publish
RUN dotnet publish "PioneerControlToMqtt.csproj" -c Release -o /app/publish --self-contained false --no-restore
 
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PioneerControlToMqtt.dll"]